### ISSUE TITLE
Webtoon - nieaktualne/błędne informacje na stronie

### ISSUE THREAD

**Issue by masay644** [MattyMroz/SoloLeveling#12]
Cześć, 
wiem że rozdziały są wyłączone, ale na stronie dalej są informacje o dostępności i link który do nich odsyła. Trochę bez sensu, bo wprowadza ludzi w błąd.
Prośba o informacje czy rozdziały będą w przyszłości dostępne, bo jeśli nie, to jaki jest cel pozostawienia tej części dotyczącej manhwy?

![image](https://github.com/user-attachments/assets/21482058-91a1-4ed6-b492-474d5c151a01)

**Comment by MattyMroz** [comment]
Zrobiłem to tak, że u mnie działa, a u was jest lub nie w zależności od przełącznika...
Strona nie jest indeksowana w Google, a ruch jest znikomy - aktualizacja tego jest nieważna.
To samo z sekcją anime.
