### ISSUE TITLE
Brak rozdziałów i pytanie 

### ISSUE THREAD

**Issue by Beru500** [MattyMroz/SoloLeveling#13]
Nie wyświetlają się rozdziały i domyślam się że jest to spowodowane przez prawa autorskie lecz nie ma żadnej możliwości udostępnienia gdzie indziej np discord lub coś podobnego? Jeżeli nie to szkoda bo nie mam co czytać w wolnej chwili :)

**Comment by MattyMroz** [comment]
Dano nie dostałem tyle pytań o błędy, przy działającej funkcjonalności.
Wszystkie nowości są ogłaszane na Discord: https://discord.gg/u6XV7NwN5Z
Nie udostępniam, ale jak ktoś jest, sprytny to sobie poradzi.
Zamykam.
