### ISSUE TITLE
Braki w chapterach

### ISSUE THREAD

**Issue by dynamichny** [MattyMroz/SoloLeveling#2]
Hej, przy chapterze 86 zauważyłem że chaptery nie zawierają wszystkich stron, tu jest nawet taki przypadek że ilustracje są ucinane w połowie, czy jest to spowodowane brakiem ich w polskiej wersji?

**Comment by MattyMroz** [comment]
(Sesja - mogłem teraz dopiero sprawdzić) Hmmm, faktycznie są straszne braki, czy to się dzieje też w innych charterach??? 
Jest to spowodowane raczej moim zaniedbaniem, każdy panel ręcznie pobierałem i upscalowałem do 4K, więc naturalnie gdzieś coś się musiało zapodziać. Robiłem to ponad rok temu i do tej pory tak wisi. Jak masz jakieś miejsca, gdzie są jeszcze jakieś braki to pisz, na dniach naprawie.

**Comment by MattyMroz** [comment]
Dodano brakujące panele w rozdziele 86 ✨
Zamykam.
