### ISSUE TITLE
Webtoon się przestał ładować

### ISSUE THREAD

**Issue by Qubista** [MattyMroz/SoloLeveling#7]

**Comment by MattyMroz** [comment]
Webtoon został udostępniony na tydzień z okazji premiery kinowej tego tytułu w Polsce i został wyłączony ręcznie. To zamierzone działanie. 
Zamykam.

**Comment by Qubista** [comment]
Rozumiem. A czemu usuwasz? Copyright jakiś czy co?

**Comment by MattyMroz** [comment]
Dokładnie

**Comment by Macieyyy** [comment]
czy jeszcze kiedyś to udostępnisz???
